### ISSUE TITLE
App.js isn't in a servable location from :kit/cljs module

### ISSUE THREAD

**Issue by crimsonhawk47** [kit-clj/modules#11]
Not sure if there's a way to use app.js that I'm not doing, but currently, the public folder is copied from

`target/classes/cljsbuild/public`

to 

`target/classes/`

But it looks like the public folder is supposed to be `target/classes/public`. 

Is this a mistake? My built uberjar can't import `app.js` unless I change that path

**Comment by yogthos** [comment]
You're right that's a typo. I just updated the module to use `target/classes/public` as the target folder to copy assets into.
