### ISSUE TITLE
Refactor ctmx to inherit from htmx module

### ISSUE THREAD

**Issue by markokocic** [kit-clj/modules#16]
I see that we have both ctmx and htmx module, ctmx basically being an example on top of htmx module.

@whamtet maybe it would make sense to refactor ctmx module to extend from htmx module and add only additional assets, instead of duplicating?

**Comment by yogthos** [comment]
That shouldn't be too hard to do if it's just additive changes. We'd just need to add `:requires [:kit/htmx]` in `config.edn` for `kit/ctmx, and that will generate all the assets from the required module.

**Comment by whamtet** [comment]
Yes we could do that but what if the htmx module changes and we don't want the ctmx module to change?  My instinct is to try and keep things simple.

**Comment by markokocic** [comment]
htmx module is not meant to change. It should be just a minimal example to get started, and the only reason to change would be in case kit itself changes and it needs to comply, or when bumping a dependency.

Since both modules share the code, it makes sense for ctmx to inherit from htmx. The other possibility is to merge ctmx and htmx modules into one module, and have two separate profiles, one for bare htmx, and another for htmx+ctmx.

> My instinct is to try and keep things simple.

That's also fine.

**Comment by yogthos** [comment]
I don't have strong feelings on this one. So, whichever method you guys think would work best I'm ok with here. Since the modules are small, it's probably not a huge concern to keep them separate for now.

**Comment by whamtet** [comment]
Let's close for now, but bear it in mind.  If we keep modifying the htmx template and find we need to make matching changes in ctmx then it would make sense to have ctmx require htmx as @yogthos suggested.
