### ISSUE TITLE
Auth module installs asset in wrong dir?

### ISSUE THREAD

**Issue by gerdint** [kit-clj/modules#18]
I wonder if the destination path on this line should perhaps be `.../web/middleware/auth.clj`? (i.e. not in routes directory)

https://github.com/kit-clj/modules/blob/defba54ad7030e4e4ebbac95a390784e9df5bd10/auth/config.edn#L4

**Comment by yogthos** [comment]
Ah yeah, updated to use `web/middleware/auth.clj` as the path. Let me know if it looks good on your end.

**Comment by gerdint** [comment]
Well, i re-sycned my modules and that looks good.
