### ISSUE TITLE
Dependency issue between htmx and simpleui modules

### ISSUE THREAD

**Issue by aleixmorgadas** [kit-clj/modules#26]
I identified an issue when I installed both modules.

- HTMX uses [`{hiccup/hiccup {:mvn/version "1.0.5"}}`](https://github.com/kit-clj/modules/blob/master/htmx/config.edn#L19)
- SimpleUI uses [`hiccup/hiccup {:mvn/version "2.0.0-alpha2"}`](https://github.com/whamtet/simpleui/blob/main/deps.edn#L4C12-L4C55)

It causes the project to break with the next error:
```
Could not locate hiccup2/core__init.class, hiccup2/core.clj
```

I fixed it by upgrading the dependency on my `deps.edn` to the newest version of `hiccup`.

**Comment by yogthos** [comment]
Thanks for the heads up, I've bumped up hiccup version for the htmx module.
